### ISSUE TITLE
UI displaying on script load makes esx_identity registry UI not display

### ISSUE THREAD

**Issue by SW1FT** [GMA950/esx_np_skinshop_v2#9]
Title is self-explanatory, the fact that the UI for this script pops up during the script loading phase (bridge loading screen) makes it so that the latest version of esx_identity cannot show its registry dialog UI when creating a character.

Let me know if you need more info.

**Comment by HezimX** [comment]
Yes i can confirm esx_identity won't show on first spawn

**Comment by giorgos94** [comment]
I also confirm this issue and would sincerely ask for some support from the developer of this resource.

Thanks!

**Comment by giorgos94** [comment]
I found a “fix” for now when it comes to trew_hud_ui not appearing along with this script.

Go on trew_hud_ui/client/client.lua and insert on line #672: Citizen.Wait(10000)

So, the result will be:

AddEventHandler(‘esx:onPlayerSpawn’, function()
Citizen.Wait(10000)
SendNUIMessage({ action = ‘ui’, config = Config.ui })
SendNUIMessage({ action = ‘setFont’, url = Config.font.url, name = Config.font.name })
SendNUIMessage({ action = ‘setLogo’, value = Config.serverLogo })

From my experiments I noticed that without this temporary solution, sometimes the trew_hud_ui will load while some other times it won’t. For me, with a decent pc it loads like half the time. For my friends with a bad one it never loaded. There must be some conflict between trew_hud_ui and np_skinshop_v2 and by adding a decent delay before trew_hud_ui loads, it seems like the issue is solved.
I did try to make it like 5000ms but for some people it just didn’t load, so I made it quite higher to make sure that everyone’s ui is loading.

I’m not sure about how we can actually solve the root of the problem here but at least there is your workaround for now.

Have fun!
